# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "#about"
#  weight = 10

[[main]]
  name = "By application"
  url = "#applications"
  weight = 20

[[main]]
  name = "By device"
  url = "/category"
  weight = 30

[[main]]
  name = "Featured"
  url = "#featured"
  weight = 40

[[main]]
  name = "Recent "
  url = "#publications"
  weight = 50
  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 60

[[main]]
  name = "Search publications"
  url = "/publication"
  weight = 70


#[[main]]
#  name = "Tags"
#  url = "#tags"
#  weight = 70

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 70
